apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: airflow
spec:
  type: Scala                          # Java/Scala/Python/R — choose Scala here
  mode: cluster
  image: apache/spark:3.3.1            # image that exists on Docker Hub (change if needed)
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.3.1.jar"
  sparkVersion: "3.3.1"
  restartPolicy:
    type: Never
  driver:
    cores: 0.1
    coreLimit: "500m"
    memory: "512m"
    serviceAccount: default
    labels:
      version: 3.3.1
  executor:
    cores: 0.1
    instances: 1
    memory: "512m"
    labels:
      version: 3.3.1
